<?php

/**
 * Implementation of hook_menu().
 */
 
function ownthatpage_menu() {
  $items['admin/settings/ownthatpage'] = array(
    'title' => 'Own that page settings',
    'description' => 'Configure what pages to own and how settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ownthatpage_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ownthatpage.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function ownthatpage_perm() {
  $perms =  explode("\n", variable_get('ownthatpage_perm', ""));
  if ($perms) {
    array_walk($perms,'ownthatpagecleaner');
    return array_filter($perms);
  }
  
}
function ownthatpagecleaner(&$value) {
    $value = check_plain(trim($value));   
}


/**
 * Implementation of hook_menu_alter().
 */
function ownthatpage_menu_alter(&$items) {
  $paths_var = variable_get('ownthatpage', "node,administer nodes\nnode/add,administer nodes");
  $paths = explode("\n",$paths_var);
  $processed = array(); 
  // go through each menu item
  foreach ($paths as $path) {
    $perm = '';
    list($path, $perm) = explode(",",$path);
    $path = trim($path);
    $perm = trim($perm);
    if (!empty($path)) {
      $processed[$path] = $perm; 
    }
  }
  
  foreach($items as $path => $info) {
    foreach($processed as $test => $perm) {
      if (drupal_match_path($path, $test)) {
        if (!empty($perm) && $perm != 'do not own that page') {
          unset($items[$path]['access callback']);
          $items[$path]['access arguments'] = array($perm);
        } elseif(empty($perm)) {
          unset($items[$path]);
        }
        break;
      }
    }
  }
}
